# Site settings
title: Diego Avendaño Peces
description: 'Personal website for Diego Avendano Peces'
url: 'https://diego09310.github.io'
baseurl: ''
profilepic: '/assets/images/profile.jpg'
bkimage: '/assets/images/bk.jpg'
paginate: 10

author:
  name: 'Diego Avendaño Peces'
  description: Tinkering, programming, and sometimes climbing.
  email: davendan92@gmail.com
  twitter_username: diego09310
  github_username: diego09310 
  gitlab_username: diego09310 
  linkedin_username: diegoavendanopeces/en

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', TODO, LICENSE, 'screenshot-overview.png']

google_analytics: G-ENQJPMV4Z3
font_awesome: 'a0a0a3b54d.js'
disqus-shortname: "diego09310-github-io"